apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"application":"fleetshard-sync"},"name":"fleetshard-sync","namespace":"acsms"},"spec":{"replicas":1,"selector":{"matchLabels":{"application":"fleetshard-sync"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"application":"fleetshard-sync"}},"spec":{"containers":[{"command":["sh","-c","/usr/local/bin/fleetshard-sync"],"env":[{"name":"KUBECONFIG","value":"/secrets/kubeconfig"},{"name":"CLUSTER_ID","value":"1234567890abcdef1234567890abcdef"},{"name":"FLEET_MANAGER_ENDPOINT","value":"http://fleet-manager:8000"},{"name":"RHSSO_SERVICE_ACCOUNT_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"rhsso-service-account-client-id","name":"fleetshard-sync","optional":false}}},{"name":"RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"rhsso-service-account-client-secret","name":"fleetshard-sync","optional":false}}},{"name":"RUNTIME_POLL_PERIOD","value":"10s"},{"name":"MANAGED_DB_ENABLED","value":""},{"name":"MANAGED_DB_SECURITY_GROUP","value":""},{"name":"MANAGED_DB_SUBNET_GROUP","value":""},{"name":"MANAGED_DB_PERFORMANCE_INSIGHTS","value":""},{"name":"AWS_ROLE_ARN","valueFrom":{"secretKeyRef":{"key":"aws-role-arn","name":"fleetshard-sync"}}}],"image":"fleet-manager:2023-01-24.1.e67c2c6-12-gf290b3e7b2-dirty","imagePullPolicy":"IfNotPresent","name":"fleetshard-sync","resources":{"limits":{"cpu":"200m","memory":"300Mi"},"requests":{"cpu":"200m","memory":"300Mi"}},"volumeMounts":[{"mountPath":"/secrets","name":"secrets"},{"mountPath":"/config","name":"config"}]}],"restartPolicy":"Always","volumes":[{"name":"secrets","secret":{"optional":false,"secretName":"fleetshard-sync"}},{"configMap":{"name":"config"},"name":"config"}]}}}}
  creationTimestamp: "2023-01-31T14:38:14Z"
  generation: 1
  labels:
    application: fleetshard-sync
  name: fleetshard-sync
  namespace: acsms
  resourceVersion: "1177"
  uid: 3c3d007a-c90f-4ca8-8479-b98fe55366ff
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: fleetshard-sync
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: fleetshard-sync
    spec:
      containers:
      - command:
        - sh
        - -c
        - /usr/local/bin/fleetshard-sync
        env:
        - name: KUBECONFIG
          value: /secrets/kubeconfig
        - name: CLUSTER_ID
          value: 1234567890abcdef1234567890abcdef
        - name: FLEET_MANAGER_ENDPOINT
          value: http://fleet-manager:8000
        - name: RHSSO_SERVICE_ACCOUNT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: rhsso-service-account-client-id
              name: fleetshard-sync
              optional: false
        - name: RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: rhsso-service-account-client-secret
              name: fleetshard-sync
              optional: false
        - name: RUNTIME_POLL_PERIOD
          value: 10s
        - name: MANAGED_DB_ENABLED
        - name: MANAGED_DB_SECURITY_GROUP
        - name: MANAGED_DB_SUBNET_GROUP
        - name: MANAGED_DB_PERFORMANCE_INSIGHTS
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              key: aws-role-arn
              name: fleetshard-sync
        image: fleet-manager:2023-01-24.1.e67c2c6-12-gf290b3e7b2-dirty
        imagePullPolicy: IfNotPresent
        name: fleetshard-sync
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          optional: false
          secretName: fleetshard-sync
      - configMap:
          defaultMode: 420
          name: config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-31T14:38:15Z"
    lastUpdateTime: "2023-01-31T14:38:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-31T14:38:14Z"
    lastUpdateTime: "2023-01-31T14:38:15Z"
    message: ReplicaSet "fleetshard-sync-7859856855" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
