- label:
    app: rhacs-operator
    control-plane: controller-manager
  name: rhacs-operator-controller-manager
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rhacs-operator
        control-plane: controller-manager
    strategy: {}
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: manager
        labels:
          app: rhacs-operator
          control-plane: controller-manager
      spec:
        containers:
          - args:
              - --health-probe-bind-address=:8081
              - --metrics-bind-address=127.0.0.1:8080
              - --leader-elect
            env:
              - name: RELATED_IMAGE_MAIN
              - name: RELATED_IMAGE_SCANNER
              - name: RELATED_IMAGE_SCANNER_SLIM
              - name: RELATED_IMAGE_SCANNER_DB
              - name: RELATED_IMAGE_SCANNER_DB_SLIM
              - name: RELATED_IMAGE_COLLECTOR_SLIM
              - name: RELATED_IMAGE_COLLECTOR_FULL
              - name: RELATED_IMAGE_ROXCTL
              - name: RELATED_IMAGE_CENTRAL_DB
              - name: MEMORY_LIMIT_BYTES
                valueFrom:
                  resourceFieldRef:
                    containerName: manager
                    divisor: '0'
                    resource: limits.memory
            image: quay.io/stackrox-io/stackrox-operator:0.0.1
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8081
              initialDelaySeconds: 15
              periodSeconds: 20
            name: manager
            ports:
              - containerPort: 9443
                name: webhook-server
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /readyz
                port: 8081
              initialDelaySeconds: 5
              periodSeconds: 10
            resources:
              limits:
                cpu: 200m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 200Mi
            securityContext:
              allowPrivilegeEscalation: false
          - args:
              - --secure-listen-address=0.0.0.0:8443
              - --upstream=http://127.0.0.1:8080/
              - --logtostderr=true
              - --v=0
            image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
            name: kube-rbac-proxy
            ports:
              - containerPort: 8443
                name: https
                protocol: TCP
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 5m
                memory: 64Mi
        securityContext:
          runAsNonRoot: true
        serviceAccountName: rhacs-operator-controller-manager
        terminationGracePeriodSeconds: 10
