apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: rhacs-operator
    control-plane: controller-manager
  name: rhacs-operator-controller-manager
  namespace: stackrox-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rhacs-operator
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rhacs-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        env:
        - name: ROX_OPERATOR_MAIN_REGISTRY
          value: quay.io/rhacs-eng
        - name: ROX_OPERATOR_COLLECTOR_REGISTRY
          value: quay.io/rhacs-eng
        - name: OPERATOR_CONDITION_NAME
          value: rhacs-operator.v3.73.1
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /apiserver.local.config/certificates
          name: apiservice-cert
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: RELATED_IMAGE_MAIN
        - name: RELATED_IMAGE_SCANNER
        - name: RELATED_IMAGE_SCANNER_SLIM
        - name: RELATED_IMAGE_SCANNER_DB
        - name: RELATED_IMAGE_SCANNER_DB_SLIM
        - name: RELATED_IMAGE_COLLECTOR_SLIM
        - name: RELATED_IMAGE_COLLECTOR_FULL
        - name: RELATED_IMAGE_ROXCTL
        - name: RELATED_IMAGE_DOCS
        - name: RELATED_IMAGE_CENTRAL_DB
        - name: ROX_OPERATOR_MAIN_REGISTRY
          value: quay.io/rhacs-eng
        - name: ROX_OPERATOR_COLLECTOR_REGISTRY
          value: quay.io/rhacs-eng
        - name: OPERATOR_CONDITION_NAME
          value: rhacs-operator.v3.73.1
        image: quay.io/rhacs-eng/stackrox-operator:3.73.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /apiserver.local.config/certificates
          name: apiservice-cert
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: rhacs-operator-controller-manager
      serviceAccountName: rhacs-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: apiservice-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
          secretName: rhacs-operator-controller-manager-service-cert
      - name: webhook-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: rhacs-operator-controller-manager-service-cert

